from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('login_success/', views.login_success, name = 'login_success'),
    path('unauthorized_access/', views.UnauthorizeView.as_view(), name='unauthorize_view'),
    path('', views.IndexView.as_view(), name = 'index_view'),
    path('admin_home/', views.AdminView.as_view(), name = 'admin_view'),
    path('teacher/', views.TeacherView.as_view(), name = 'teacher_view'),
    path('student/', views.StudentView.as_view(), name = 'student_view'),
    path('create/admin/', views.CreateAdminUser.as_view(), name = 'create_admin_user'),
    path('admin_home/manage_data', views.ManageData.as_view(), name = 'manage_data_nav'),
    path('admin_home/manage_data/departments/new', views.CreateDepartment.as_view(), name = 'department_create'),
    path('admin_home/manage_data/departments/edit/<str:pk>', views.UpdateDepartment.as_view(), name = 'department_update'),
    path('admin_home/manage_data/departments/delete/<str:pk>', views.DeleteDepartment.as_view(), name = 'department_delete'),
    path('admin_home/manage_data/courses/new', views.CreateCourse.as_view(), name = 'course_create'),
    path('admin_home/manage_data/courses/edit/<str:pk>', views.UpdateCourse.as_view(), name = 'course_update'),
    path('admin_home/manage_data/courses/delete/<str:pk>', views.DeleteCourse.as_view(), name = 'course_delete'),
    path('admin_home/manage_data/classes/new', views.CreateClass.as_view(), name = 'class_create'),
    path('admin_home/manage_data/classes/edit/<str:pk>', views.UpdateClass.as_view(), name = 'class_update'),
    path('admin_home/manage_data/classes/delete/<str:pk>', views.DeleteClass.as_view(), name = 'class_delete'),
    path('admin_home/manage_data/teachers/new', views.CreateTeacher.as_view(), name = 'teacher_create'),
    path('admin_home/manage_data/teachers/edit/<str:pk>', views.UpdateTeacher.as_view(), name = 'teacher_update'),
    path('admin_home/manage_data/teachers/delete/<str:pk>', views.DeleteTeacher.as_view(), name = 'teacher_delete'),
    path('admin_home/manage_data/assign/new', views.CreateAssign.as_view(), name = 'assign_create'),
    path('admin_home/manage_data/assign/edit/<int:pk>', views.UpdateAssign.as_view(), name = 'assign_update'),
    path('admin_home/manage_data/assign/delete/<int:pk>', views.DeleteAssign.as_view(), name = 'assign_delete'),
    path('admin_home/manage_data/assign_time_slots/new', views.AssignTimeSlots.as_view(), name = 'assign_time_create'),
    path('admin_home/manage_data/assign_time_slots/delete/<int:pk>', views.DeleteTimeSlots.as_view(), name = 'assign_time_delete'),
    path('admin_home/manage_data/students/new', views.CreateStudent.as_view(), name = 'student_create'),
    path('admin_home/manage_data/students/edit/<str:pk>', views.UpdateStudent.as_view(), name = 'student_update'),
    path('admin_home/manage_data/students/delete/<str:pk>', views.DeleteStudent.as_view(), name = 'student_delete'),
    path('teacher/classes', views.TeacherClassView.as_view(), name = 'teacher_class_view'),
    path('teacher/class/date/<int:assign_id>', views.TeacherClassDatesView.as_view(), name = 'teacher_class_detail_view'),
    path('teacher/class/date/<int:assign_class_id>/attendance', views.TeacherAttendanceView.as_view(), name = 'teacher_attendance_view'),
    path('teacher/class/date/<int:assign_class_id>/attendance/edit', views.EditAttendance.as_view(), name = 'edit_attendance'),
    path('teacher/class/date/<int:assign_class_id>/attendance/cancel', views.CancelClassView.as_view(), name = 'cancel_class'),
    path('teacher/class/<int:assign_id>/extra_class', views.ExtraClass.as_view(), name = 'extra_class'),
    path('teacher/<int:assign_id>/students/attendance', views.ViewStudents.as_view(), name = 'view_students'),
    path('teacher/<str:roll_number>/<str:course_id>/attendance', views.AttendanceDetailView.as_view(), name = "attendance_detail_view"),
    path('teacher/<int:attendance_id>/change_attendance', views.ChangeAttendance.as_view(), name = "change_attendance"),
    path('teacher/classes/marks', views.TeacherViewMarks.as_view(), name = "teacher_view_marks"),
    path('teacher/class/marks/<int:assign_id>', views.TeacherMarksListView.as_view(), name = "teacher_marks_view"),
    path('teacher/class/marks/<int:marks_class_id>/new', views.TeacherMarksEntryView.as_view(), name = 'teacher_marks_entry'),
    path('teacher/class/marks/<int:marks_class_id>/edit', views.TeacherEditMarksView.as_view(), name = 'teacher_marks_edit'),
    path('teacher/<int:assign_id>/students/marks', views.TeacherViewStudentMarks.as_view(), name = "teacher_view_student_marks"),
    path('teacher/<str:teacher_id>/timetable', views.TeacherTimetable.as_view(), name = 'teacher_timetable'),
    path('teacher/<int:assign_time_id>/free_teachers', views.FreeTeachers.as_view(), name = 'free_teachers'),
    path('teacher/classes/reports', views.TeacherReportClassesView.as_view(), name = 'teacher_report_classes'),
    path('teacher/<int:assign_id>/class/report', views.TeacherReportView.as_view(), name = "teacher_report_view"),
    path('student/<str:roll_number>/attendance', views.StudentAttendanceView.as_view(), name = "student_attendance"),
    path('student/<str:roll_number>/<str:course_id>/attendance', views.StudentAttendanceDetailView.as_view(), name = 'student_attendance_detail'),
    path('student/<str:roll_number>/marks', views.StudentMarksListView.as_view(), name = "student_marks"),
    path('student/<str:class_id>/timetable', views.StudentTimetable.as_view(), name = 'student_timetable'),
]