# Generated by Django 5.1.5 on 2025-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceclass',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
