# Generated by Django 5.1.5 on 2025-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_attendanceclass_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hod',
            field=models.BooleanField(default=False, verbose_name='HOD Status'),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('07:30 AM - 08:30 AM', '07:30 AM - 08:30 AM'), ('08:30 AM - 09:30 AM', '08:30 AM - 09:30 AM'), ('09:30 AM - 10:30 AM', '09:30 AM - 10:30 AM'), ('11:00 AM - 11:50 PM', '11:00 AM - 11:50 PM'), ('11:50 AM - 12:40 PM', '11:50 AM - 12:40 PM'), ('12:40 PM - 01:30 PM', '12:40 PM - 01:30 PM'), ('02:30 PM - 03:30 PM', '02:30 PM - 03:30 PM'), ('03:30 PM - 04:30 PM', '03:30 PM - 04:30 PM'), ('04:30 PM - 05:30 PM', '04:30 PM - 05:30 PM')], default='07:30 AM - 08:30 AM', max_length=50),
        ),
    ]
