# Generated by Django 5.1.5 on 2025-04-11 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_user_is_hod_alter_assigntime_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.department')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.teacher')),
            ],
        ),
    ]
