# Generated by Django 5.1.5 on 2025-04-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_hod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hod',
            options={'verbose_name_plural': 'HODs'},
        ),
    ]
